name: Release Alpha Python SDK

on:
  push:
    branches:
      - main
      - det-2968/beta-cli
    paths:
      - python/sdk/**
      - .github/workflows/release-alpha.yml

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: build sdk dist
        id: buildsdkreleasedist
        env:
          SETUP_CFG=./setup.cfg
        working-directory: ./python/sdk
        run: |
          setup_semver=$(grep version setup.cfg | cut -d' ' -f3)

          CURRENT_VERSION=$(grep -E '^version\s*=' "$SETUP_CFG" | awk -F '=' '{print $2}' | tr -d '[:space:]')

          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          PATCH="${BASH_REMATCH[3]}"

          NEW_PATCH=$((PATCH + 1))

          GIT_COUNT=$(git rev-list --count HEAD)

          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}a${GIT_COUNT}"

          sed -i -E "s/^(version\s*=\s*).*/\1$NEW_VERSION/" "$SETUP_CFG"

          echo "semver=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          echo "gitcount=$GIT_COUNT" >> "$GITHUB_OUTPUT"

          python -m pip install -U build
          python -m build

      - name: build cli dist
        id: buildclireleasedist
        env:
          SETUP_CFG=./setup.cfg
        working-directory: ./python/cli
        run: |

          sed -i -E 's/^(name\s*=\s*).*/\1prelude-cli-beta/' "$SETUP_CFG"
          sed -i -E 's/^(version\s*=\s*).*/\1${{ env.gitcount }}/' "$SETUP_CFG"
          sed -i -E 's/prelude-sdk\s*==\s*.*$/prelude-sdk == ${{ env.semver }}/' "$SETUP_CFG"

          python -m build

      - name: publish sdk release dist to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/sdk/dist

      - name: publish cli release dist to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/cli/dist

      - name: tag repo
        if: success()
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
          tag="python/sdk/${{ needs.release-build.outputs.semver }}"
          cli_tag="python/cli_beta/${{ env.gitcount }}"

          git tag $tag
          git tag $cli_tag

          git push origin $tag
          git push origin $cli_tag
      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Python alpha sdk and beta cli published (${{ github.triggering_actor }}): ${{ github.ref }} - ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Python alpha sdk and beta cli published (${{ github.triggering_actor }}): ${{ github.ref }} - ${{ job.status }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.US2_SLACK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
